// packages/core/src/activities/catalog.ts
// Hand-curated. DO NOT modify copy with an LLM.
// All 36 activities authored by human. See activity-catalog SKILL.md for rules.

export type ActivityCategory = 'PhysicalReset' | 'ContextPreserving' | 'WriteOnly' | 'Diffuse';
export type WaitBand = 'short' | 'medium-short' | 'medium-long' | 'long';

export interface Activity {
  id: string;
  category: ActivityCategory;
  waitBands: WaitBand[];
  title: string;
  body: string;
  durationHintSec: number;
  requiresInput: false;
  citation?: string;
}

export const catalog: Activity[] = [
  // ── PhysicalReset (12) ────────────────────────────────────────────────────

  {
    id: 'pr-2020',
    category: 'PhysicalReset',
    waitBands: ['short', 'medium-short'],
    title: 'Look 20 feet away',
    body: 'Pick the farthest object you can see and rest your eyes on it for 20 seconds.',
    durationHintSec: 20,
    requiresInput: false,
    citation: 'henning1997',
  },
  {
    id: 'pr-shoulder-roll',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Roll your shoulders back',
    body: 'Three slow rolls back, then three forward. Notice where the tension was.',
    durationHintSec: 15,
    requiresInput: false,
  },
  {
    id: 'pr-jaw',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Unclench your jaw',
    body: 'Let your tongue drop from the roof of your mouth. Soften the muscles around your eyes.',
    durationHintSec: 10,
    requiresInput: false,
  },
  {
    id: 'pr-breath-3',
    category: 'PhysicalReset',
    waitBands: ['short', 'medium-short'],
    title: 'Three slow breaths',
    body: 'Inhale four counts, hold two, exhale six. Repeat twice more.',
    durationHintSec: 30,
    requiresInput: false,
    citation: 'henning1997',
  },
  {
    id: 'pr-water',
    category: 'PhysicalReset',
    waitBands: ['short', 'medium-short'],
    title: 'Drink water',
    body: 'Mild dehydration measurably impairs cognition. The wait is your reminder.',
    durationHintSec: 30,
    requiresInput: false,
  },
  {
    id: 'pr-stand',
    category: 'PhysicalReset',
    waitBands: ['short', 'medium-short'],
    title: 'Stand up',
    body: 'Just stand. Hip flexors shorten quickly when seated. No commitment to anything else.',
    durationHintSec: 15,
    requiresInput: false,
    citation: 'henning1997',
  },
  {
    id: 'pr-neck-tilt',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Slow neck tilt',
    body: "Right ear toward right shoulder, hold five seconds. Left side. Don't force it.",
    durationHintSec: 20,
    requiresInput: false,
  },
  {
    id: 'pr-hand-stretch',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Open and close your hands',
    body: 'Spread your fingers wide, then make loose fists. Five reps. Wrist circles after.',
    durationHintSec: 20,
    requiresInput: false,
  },
  {
    id: 'pr-feet-down',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Both feet flat on the floor',
    body: 'Notice the contact. Push gently into the ground. Re-engage your posture.',
    durationHintSec: 10,
    requiresInput: false,
  },
  {
    id: 'pr-look-up',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Look up at the ceiling',
    body: 'Slow ten-second tilt of your head back. Reverse the screen-hunch.',
    durationHintSec: 15,
    requiresInput: false,
  },
  {
    id: 'pr-soft-eyes',
    category: 'PhysicalReset',
    waitBands: ['short'],
    title: 'Soften your gaze',
    body: 'Stop focusing on the screen for ten seconds. Let your vision blur.',
    durationHintSec: 10,
    requiresInput: false,
  },
  {
    id: 'pr-stretch-side',
    category: 'PhysicalReset',
    waitBands: ['short', 'medium-short'],
    title: 'Side stretch',
    body: 'Right arm overhead, lean gently left. Switch sides. Breathe through it.',
    durationHintSec: 30,
    requiresInput: false,
  },

  // ── ContextPreserving (10) ────────────────────────────────────────────────

  {
    id: 'cp-reread-prompt',
    category: 'ContextPreserving',
    waitBands: ['medium-short', 'medium-long'],
    title: 'Re-read your prompt',
    body: 'What did you ask the model to do? Read it back to yourself before the response arrives.',
    durationHintSec: 30,
    requiresInput: false,
    citation: 'mark2008',
  },
  {
    id: 'cp-expected-shape',
    category: 'ContextPreserving',
    waitBands: ['medium-short', 'medium-long'],
    title: 'Picture the expected output',
    body: 'What does a correct answer look like? Sketch it mentally before you read the actual one.',
    durationHintSec: 45,
    requiresInput: false,
    citation: 'mark2008',
  },
  {
    id: 'cp-edge-case',
    category: 'ContextPreserving',
    waitBands: ['medium-short', 'medium-long'],
    title: 'Name one edge case',
    body: "One scenario the response should handle. Just one. Don't write it down — hold it in mind.",
    durationHintSec: 30,
    requiresInput: false,
  },
  {
    id: 'cp-assumption',
    category: 'ContextPreserving',
    waitBands: ['medium-long'],
    title: 'What assumption could be wrong?',
    body: 'Pick one premise of your prompt and stress-test it silently.',
    durationHintSec: 45,
    requiresInput: false,
    citation: 'mark2008',
  },
  {
    id: 'cp-scan-recent',
    category: 'ContextPreserving',
    waitBands: ['medium-short', 'medium-long'],
    title: 'Scan your recent work',
    body: "Scroll back through what you've done in this session. Don't edit. Just refresh context.",
    durationHintSec: 60,
    requiresInput: false,
    citation: 'mark2008',
  },
  {
    id: 'cp-simpler-version',
    category: 'ContextPreserving',
    waitBands: ['medium-long'],
    title: 'Imagine a simpler version',
    body: 'If this needed to be half as complex, what would you cut?',
    durationHintSec: 45,
    requiresInput: false,
  },
  {
    id: 'cp-10x',
    category: 'ContextPreserving',
    waitBands: ['medium-long'],
    title: 'What breaks at 10x scale?',
    body: 'Volume, users, frequency — pick one and walk it forward.',
    durationHintSec: 45,
    requiresInput: false,
  },
  {
    id: 'cp-acceptance',
    category: 'ContextPreserving',
    waitBands: ['medium-short', 'medium-long'],
    title: 'Define done',
    body: "What's the smallest signal that tells you this output is good enough to use?",
    durationHintSec: 30,
    requiresInput: false,
  },
  {
    id: 'cp-glance-prompt',
    category: 'ContextPreserving',
    waitBands: ['medium-short'],
    title: 'Read your prompt out loud',
    body: 'Quietly. Saying it changes how you hear it.',
    durationHintSec: 20,
    requiresInput: false,
    citation: 'mark2008',
  },
  {
    id: 'cp-wrong-shape',
    category: 'ContextPreserving',
    waitBands: ['medium-long'],
    title: 'What would a wrong answer look like?',
    body: 'Naming failure modes makes them easier to spot in the response.',
    durationHintSec: 45,
    requiresInput: false,
  },

  // ── WriteOnly (8) ─────────────────────────────────────────────────────────

  {
    id: 'wo-next-prompt',
    category: 'WriteOnly',
    waitBands: ['medium-long', 'long'],
    title: 'Draft your next instruction',
    body: "What's the follow-up? Type it here — it'll be waiting when the response arrives.",
    durationHintSec: 60,
    requiresInput: false,
    citation: 'cowan2010',
  },
  {
    id: 'wo-blocker',
    category: 'WriteOnly',
    waitBands: ['medium-long', 'long'],
    title: 'Note a blocker',
    body: 'Something you need to ask someone? Capture it now before it slips.',
    durationHintSec: 45,
    requiresInput: false,
    citation: 'cowan2010',
  },
  {
    id: 'wo-todo',
    category: 'WriteOnly',
    waitBands: ['medium-long', 'long'],
    title: 'Update your todo',
    body: "One line. What's done, what's next. Externalize it.",
    durationHintSec: 30,
    requiresInput: false,
    citation: 'cowan2010',
  },
  {
    id: 'wo-question',
    category: 'WriteOnly',
    waitBands: ['medium-long', 'long'],
    title: 'Log a question for later',
    body: 'Something to look up but not now. Park it.',
    durationHintSec: 30,
    requiresInput: false,
  },
  {
    id: 'wo-decision-log',
    category: 'WriteOnly',
    waitBands: ['long'],
    title: 'Note a decision you made',
    body: "Capture the why while it's fresh. Future-you will thank present-you.",
    durationHintSec: 60,
    requiresInput: false,
    citation: 'cowan2010',
  },
  {
    id: 'wo-bookmark',
    category: 'WriteOnly',
    waitBands: ['medium-long', 'long'],
    title: 'Park a link for later',
    body: "Something interesting? Save the URL. Don't read it.",
    durationHintSec: 20,
    requiresInput: false,
  },
  {
    id: 'wo-progress',
    category: 'WriteOnly',
    waitBands: ['long'],
    title: 'Log progress',
    body: 'One sentence describing where you are. Not a status update — a marker for yourself.',
    durationHintSec: 30,
    requiresInput: false,
  },
  {
    id: 'wo-handoff',
    category: 'WriteOnly',
    waitBands: ['long'],
    title: 'Write the handoff note',
    body: 'If you walked away right now, what would the next person need to know?',
    durationHintSec: 60,
    requiresInput: false,
    citation: 'cowan2010',
  },

  // ── Diffuse (6) ───────────────────────────────────────────────────────────

  {
    id: 'df-window',
    category: 'Diffuse',
    waitBands: ['long'],
    title: 'Look out a window',
    body: 'Find one. Pick a tree, a cloud, a person. Let your eyes follow without trying.',
    durationHintSec: 60,
    requiresInput: false,
    citation: 'baird2012',
  },
  {
    id: 'df-eyes-closed',
    category: 'Diffuse',
    waitBands: ['long'],
    title: 'Close your eyes',
    body: 'Sixty seconds. Not meditation. Just stop looking at things.',
    durationHintSec: 60,
    requiresInput: false,
    citation: 'baird2012',
  },
  {
    id: 'df-walk-room',
    category: 'Diffuse',
    waitBands: ['long'],
    title: 'Walk to another room',
    body: "Get water, stretch, come back. Don't pick up your phone.",
    durationHintSec: 120,
    requiresInput: false,
    citation: 'baird2012',
  },
  {
    id: 'df-doodle',
    category: 'Diffuse',
    waitBands: ['long'],
    title: 'Doodle',
    body: 'Pen, scrap paper, no goal. Hand movement occupies the part of your brain that would otherwise wait anxiously.',
    durationHintSec: 90,
    requiresInput: false,
    citation: 'baird2012',
  },
  {
    id: 'df-soften',
    category: 'Diffuse',
    waitBands: ['long'],
    title: 'Defocus',
    body: "Let the screen blur. Don't think about the prompt. Your brain is still working on it.",
    durationHintSec: 45,
    requiresInput: false,
    citation: 'baird2012',
  },
  {
    id: 'df-window-far',
    category: 'Diffuse',
    waitBands: ['long'],
    title: 'Find the farthest thing you can see',
    body: 'Notice three details about it. No reason.',
    durationHintSec: 45,
    requiresInput: false,
    citation: 'baird2012',
  },
];
